cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

env:
  secure: "QSumTvMGgT7gm/ydWBbB4kkivLWTPyWZzsPxfF1fx2Ekn+I9836s4L8sp4lKLVMlCWMTP1BTIYMB8gIY7lkdWusYz8GnHuLwVgwo0MtiKsM4dx/INBYz3X7jFlQ5zzHzYdjsZGhw0J9Ez4ef7K60+ssUUxOZIA+nZM2d+vgSrMvhVLOUmGZ+UOlv1yr9ed6hvbdNT6Nk98zqBiiEb5oly+bt6RqWeYYf7lsFAnQX7haCBZWs+Hts4ewRZziUzP1zUMB2qMNNkpZPOYXwXBfd00vCBMGk3YEaqBD7YXH8gMmgPLxCoeoriQsXx53X6IG/gAZ5ZpFW6A+TpFiYFlQB8A0pf4EWeTgR4IJ+OpWT9GLM0Z4ObYKFGe2/ZJjWH/zknB2NAjuVNmtbRgwQFaTP9JXBIFiK9VF7gW7jehXrVSGvkeVJIuOpyB+Z6y8qmKiDPWBMmBCESNhIp5DuvSmS2etGaf+/Ptb07dxoawb/YoSmOie4wGW0+1czDI5iMQFmy+pAvmcNiCNLRnK5UdwUfqv5aB2DQnEIeAe4EE1Dt1eHs+fSROuiSfQ11CekmMRMMWTO9dZF5lSmFp57HzESDddg67Pj5hKAWHre7MoZGrH+Yo3cQUm/CB+Qjxm4wP4UVUiB8n+APw2vGf9jdob+nJVANPSjI7qINOFkTb2MmdY="
language: java
jdk:
  - oraclejdk8
  
  
addons:
  sonarcloud:
    organization: "vsrs-laurentius"
    token:
      secure: "EY9V1SqI1d91L26hamjpapb5PtNrw1bVUXtP6hXCR4SYs70TI1zFMtdPTCj/ZU7RY6d+rbYzz1d5EpXvK8incfvE8gidT9gbOEJJvF49ll1oNE2eX1tX5NcvaTs8DPeu6TKW9aUIHTj0SRCuMbPW24WLd4pKRHiE+f12XTb8hMcd01ynhA5HVxyzOIpDkQxjHGHylDf14gsQgTr2IrLKQVxCKPGsyRKdJNOELds6g91G1AkmHZ1wPxWUoz6b8+kZefhnwJwfrSiPknqadsl1/Uh/lUS1LIYF2MQc4hdAeYqI2kbOwVteeDuV432cCrRll+0QUsksf/hK6c9YbU4E+CNm4lXxmVvckX5T4XeUyUOiTIti6Oc5fxiG4J7TpETOQ3y9cN2sIDI0sIYJ6gggMbM90hlwjSi2PBa+dobSh+VDwB7RUPhTPHMP3XaGP5vEvRj0X0lyieE9Et7uBDKywwV5lcAV8aBPKYsrmxKhgL/LpuLThW5adMr9QobuDZE9fXdBgUEKm65Tron6NECcZb5JZQGZ/F5kxDdJoi4DQzMC/a8tBnYNR5C0WriZxzgvktpq+VxXwEA9uF3FkhaOwiv1UZ76AaWgTkeRNyXA3adSVrO6i1lDuxTvQEavSz+co21wy6yDLerCNzqK34kyUqUaLsvBOOyigWl8My4STXc="
  
script:  
  #run all tests 
  #- mvn -P CI-BuildWithReports 
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  #- mvn clean install jacoco:report coveralls:report
  #sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN

#after_success:
#   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

branches:
  only:
  - master


jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t laurentius .
      - docker tag laurentius $DOCKER_USERNAME/laurentius
      - docker push $DOCKER_USERNAME/laurentius
#    - stage: test
#      script: docker run --rm $DOCKER_USERNAME/laurentius
